# Generated by Django 5.2.12 on 2026-05-20 16:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Property",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(blank=True, max_length=500)),
                ("city", models.CharField(max_length=120)),
                ("country", models.CharField(default="Bulgaria", max_length=120)),
                ("timezone", models.CharField(default="Europe/Sofia", max_length=64)),
                ("access_notes", models.TextField(blank=True)),
                ("cleaning_instructions", models.TextField(blank=True)),
                (
                    "default_cleaning_duration_minutes",
                    models.PositiveIntegerField(default=120),
                ),
                (
                    "default_price_eur",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=8, null=True
                    ),
                ),
                (
                    "host",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="properties",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "properties",
                "ordering": ["city", "name"],
            },
        ),
        migrations.CreateModel(
            name="ExternalCalendarConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[("ical", "iCal"), ("google", "Google Calendar")],
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("import", "Import"),
                            ("export", "Export"),
                            ("two_way", "Two-way"),
                        ],
                        default="import",
                        max_length=20,
                    ),
                ),
                ("feed_url", models.URLField(blank=True)),
                ("external_calendar_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("error", "Error"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_connections",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source", models.CharField(default="manual", max_length=120)),
                ("external_uid", models.CharField(blank=True, max_length=255)),
                ("guest_name", models.CharField(blank=True, max_length=255)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("notes", models.TextField(blank=True)),
                (
                    "property",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservations",
                        to="properties.property",
                    ),
                ),
            ],
            options={
                "ordering": ["starts_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("external_uid", ""), _negated=True),
                        fields=("property", "source", "external_uid"),
                        name="unique_external_reservation_per_property",
                    )
                ],
            },
        ),
    ]
